# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 1000
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: web
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: autumn # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
  freemarker:
    suffix: .html
    request-context-attribute: request
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

autumn:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: true # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
  database: mysql
  table:
    auto: update
    init: true
    pack: cn.org.autumn.modules

#mybatis-plus 3.x 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.org.autumn.modules.*.entity
  global-config:
    banner: false
    db-config:
      #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ASSIGN_ID:"雪花算法ID", ASSIGN_UUID:"UUID"
      id-type: AUTO
      #全局列名加反引号，防止 MySQL 保留关键字冲突
      column-format: "`%s`"
      #字段验证策略 NEVER:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", ALWAYS:"总是加入"
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_NULL
      #驼峰下划线转换
      table-underline: true
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level:
    root: info
    cn.org.autumn: info
    com.aliyun.oss: fatal
    springfox.documentation: fatal
    org.quartz: warn
    org.springframework: fatal
    org.springframework.web: warn
    org.springframework.web.servlet.DispatcherServlet: fatal
    org.springframework.web.servlet.view: fatal
    org.springframework.jmx: warn
    org.springframework.boot.web: warn
    org.springframework.boot.web.servlet: warn
    com.netflix.discovery.shared.resolver.aws: fatal
    org.springframework.boot.web.embedded: info
    com.baomidou.mybatisplus: fatal
    org.apache.shiro.session: fatal
    com.alibaba.druid: off
    org.mybatis.spring: info
    org.apache.tomcat: info
    org.apache.catalina: info
    sun.rmi.transport.tcp: info
    com.netflix: fatal
    net.sf.ehcache: fatal
    io.netty.resolver.dns: fatal

  file:
    name: file.log
    path: logs/

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapperLocations: classpath:mapper/**/*.xml